const inventoryExternalData = [
  {
    alternative_title: "Alaska",
    isbn: "0449217264",
    price: 10,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "Jurasiic Park",
    isbn: "0345370775",
    price: 8,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "The first man in Rome",
    isbn: "9780688093686",
    price: 25,
    freeShipping: false,
    isNew: false,
    isUsed: true,
    hardcover: true,
    softcover: false,
  },
  {
    alternative_title: "Red Dragon",
    isbn: "0440206154",
    price: 12,
    freeShipping: true,
    isNew: true,
    isUsed: false,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "The Thorn Birds",
    isbn: "9780380018178",
    price: 10,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "Mexico",
    isbn: "0449221873",
    price: 8,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "Hawaii",
    isbn: "0449207110",
    price: 16,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "The Alchemist",
    isbn: "9780062502186",
    price: 18,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "The Pilgrimage",
    isbn: "9780061687457",
    price: 10,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "The Game of Thrones",
    isbn: "9780553381689",
    price: 13,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "Insomnia",
    isbn: "9780451184962",
    price: 14,
    freeShipping: false,
    isNew: false,
    isUsed: true,
    hardcover: true,
    softcover: false,
  },
  {
    alternative_title: "Dreamcatcher",
    isbn: "9780340770719",
    price: 11,
    freeShipping: false,
    isNew: true,
    isUsed: false,
    hardcover: false,
    softcover: true,
  },
];
export default inventoryExternalData;
