const inventoryExternalData = [
  {
    alternative_title: "The 4-Hour Workweek",
    isbn: "9780307465351",
    price: 25,
    freeShipping: false,
    isNew: false,
    softcover: false,
  },
  {
    alternative_title: "Sam",
    isbn: "9780593447819",
    price: 9,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Eifelheim",
    isbn: "9780765340351",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Well of Ascension",
    isbn: "9780765356130",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Way of Kings",
    isbn: "9780765365279",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Knight",
    isbn: "9780765313485",
    price: 14,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Flantris",
    isbn: "9780765350374",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Ages of Chaos",
    isbn: "0756400724",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Hyperion",
    isbn: "9780553283686",
    price: 7,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Rise And Fall Of The Dinosaurs",
    isbn: "9780062490438",
    price: 17,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Power of Habit",
    isbn: "9780812981605",
    price: 17,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Desert Spear",
    isbn: "9780345524140",
    price: 12,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Eye of The World",
    isbn: "9780812511819",
    price: 16,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Congo",
    isbn: "0345378490",
    price: 17,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Dark Tower",
    isbn: "0451160525",
    price: 11,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Warded Man",
    isbn: "9780345518705",
    price: 12,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Tools of Titans",
    isbn: "9781328683786",
    price: 9,
    freeShipping: false,
    isNew: false,
    softcover: false,
  },
  {
    alternative_title: "Do What You Are",
    isbn: "9780316236737",
    price: 13,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Think Fast and Slow",
    isbn: "9780374533557",
    price: 15,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Alaska",
    isbn: "0449217264",
    price: 10,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Jurasiic Park",
    isbn: "0345370775",
    price: 8,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The first man in Rome",
    isbn: "9780688093686",
    price: 25,
    freeShipping: false,
    isNew: false,
    softcover: false,
  },
  {
    alternative_title: "Red Dragon",
    isbn: "0440206154",
    price: 12,
    freeShipping: true,
    isNew: true,
    softcover: true,
  },
  {
    alternative_title: "The Thorn Birds",
    isbn: "9780380018178",
    price: 10,
    freeShipping: true,
    isNew: false,
    isUsed: true,
    hardcover: false,
    softcover: true,
  },
  {
    alternative_title: "Mexico",
    isbn: "0449221873",
    price: 8,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Hawaii",
    isbn: "0449207110",
    price: 16,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Alchemist",
    isbn: "9780062502186",
    price: 18,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Pilgrimage",
    isbn: "9780061687457",
    price: 10,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "The Game of Thrones",
    isbn: "9780553381689",
    price: 13,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },
  {
    alternative_title: "Insomnia",
    isbn: "9780451184962",
    price: 14,
    freeShipping: true,
    isNew: false,
    softcover: false,
  },
  {
    alternative_title: "Dreamcatcher",
    isbn: "9780340770719",
    price: 11,
    freeShipping: false,
    isNew: true,
    softcover: true,
  },
  {
    alternative_title: "The Three-Body Problem",
    isbn: "9787536693968",
    price: 11,
    freeShipping: false,
    isNew: true,
    softcover: true,
  },
  {
    alternative_title: "The Panther",
    isbn: "9780446580847",
    price: 15,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },

  {
    alternative_title: "The Personal MBA",
    isbn: "9781591845577",
    price: 16,
    freeShipping: true,
    isNew: false,
    softcover: true,
  },

  {
    alternative_title: "The Courage to Be Rich",
    isbn: "1573221252",
    price: 19,
    freeShipping: true,
    isNew: false,
    softcover: false,
  },
  {
    alternative_title: "JavaScript for Web Developers",
    isbn: "9781119366447",
    price: 60,
    freeShipping: false,
    isNew: false,
    softcover: true,
  },
];
export default inventoryExternalData;
